server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/cafe?useSSL=false&useUnicode=true&ServerTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

naver:
  uri:
    local: https://openapi.naver.com/v1/search/local.json
    image: https://openapi.naver.com/v1/search/image
  id: qGOr2l4kuSwvAMYd0in_
  secret: uDks8vbZb7
